module.exports = {
  ayanamshas: {
    0: { id: 0, name: "FAGAN_BRADLEY " },
    1: { id: 1, name: "LAHIRI " },
    2: { id: 2, name: "DELUCE " },
    3: { id: 3, name: "RAMAN " },
    4: { id: 4, name: "USHASHASHI " },
    5: { id: 5, name: "KRISHNAMURTI " },
    6: { id: 6, name: "DJWHAL_KHUL " },
    7: { id: 7, name: "YUKTESHWAR " },
    8: { id: 8, name: "JN_BHASIN " },
    9: { id: 9, name: "BABYL_KUGLER1 " },
    10: { id: 10, name: "BABYL_KUGLER2 " },
    11: { id: 11, name: "BABYL_KUGLER3 " },
    12: { id: 12, name: "BABYL_HUBER " },
    13: { id: 13, name: "BABYL_ETPSC " },
    14: { id: 14, name: "ALDEBARAN_15TAU " },
    15: { id: 15, name: "HIPPARCHOS " },
    16: { id: 16, name: "SASSANIAN " },
    17: { id: 17, name: "GALCENT_0SAG " },
    18: { id: 18, name: "J2000 " },
    19: { id: 19, name: "J1900 " },
    20: { id: 20, name: "B1950 " },
    21: { id: 21, name: "SURYASIDDHANTA " },
    22: { id: 22, name: "SURYASIDDHANTA_MSUN " },
    23: { id: 23, name: "ARYABHATA " },
    24: { id: 24, name: "ARYABHATA_MSUN " },
    25: { id: 25, name: "SS_REVATI " },
    26: { id: 26, name: "SS_CITRA " },
    27: { id: 27, name: "TRUE_CITRA " },
    28: { id: 28, name: "TRUE_REVATI " },
    29: { id: 29, name: "TRUE_PUSHYA " },
    30: { id: 30, name: "GALCENT_RGILBRAND " },
    31: { id: 31, name: "GALEQU_IAU1958 " },
    32: { id: 32, name: "GALEQU_TRUE " },
    33: { id: 33, name: "GALEQU_MULA " },
    34: { id: 34, name: "GALALIGN_MARDYKS " },
    35: { id: 35, name: "TRUE_MULA " },
    36: { id: 36, name: "GALCENT_MULA_WILHELM " },
    37: { id: 37, name: "ARYABHATA_522 " },
    38: { id: 38, name: "BABYL_BRITTON " },
    39: { id: 39, name: "TRUE_SHEORAN " },
    40: { id: 40, name: "GALCENT_COCHRANE " },
    41: { id: 41, name: "GALEQU_FIORENZA " },
    42: { id: 42, name: "VALENS_MOON " },
  },
};
